#!/bin/bash
INPUT=$1
TEMP=$2
OUTPUT=$3
ARG=$4

if [ -e $TEMP ]; then
    echo false
else
    ffmpeg -n -hide_banner -nostats -loglevel panic -threads 1 -i $INPUT $ARG $TEMP
    if [ -e $TEMP ]; then
        mv $TEMP $OUTPUT
        echo true
    else
        echo 0
    fi
fi
