#!/bin/bash
INPUT=$1
TEMP=$2
OUTPUT=$3

if [ -e $TEMP ]; then
    echo false
else
    ffmpeg -n -hide_banner -nostats -loglevel panic -threads 1 -i $INPUT -c:v libvpx -crf 10 -b:v 1M -c:a libvorbis $TEMP
    if [ -e $TEMP ]; then
        mv $TEMP $OUTPUT
        echo true
    else
        echo 0
    fi
fi
