default: &default
  adapter: postgresql
  encoding: unicode
  host: 172.23.64.1
  pool: 3

development:
  <<: *default
  database: projectvinyl_development

test:
  <<: *default
  database: projectvinyl_test

production:
  <<: *default
  database: projectvinyl
