Rails.application.routes.draw do
  devise_for :users
  
  get 'stars' => 'album#starred'
  get 'search' => 'search#index'
  get 'ajax/search' => 'search#page'
  
  get 'staff' => 'staff#index'


  get 'copyright' => 'staff#copyright'
  get 'fairuse' => 'staff#copyright'
  get 'policy' => 'staff#policy'
  get 'terms' => 'staff#policy'
  get 'ajax/donate' => 'staff#donate'
  
  get 'admin' => 'admin#view'
  get 'admin/report/view/:id' => 'admin#view_report'
  get 'admin/album/:id' => 'admin#album'
  get 'admin/video/:id' => 'admin#video'
  put 'admin/video/reprocess' => 'admin#reprocessVideo'
  put 'admin/video/resetthumb' => 'admin#extractThumbnail'
  get 'ajax/admin/videos/hidden' => 'admin#page_hidden'
  get 'ajax/admin/videos/unprocessed' => 'admin#page_unprocessed'
  get 'admin/artist/:id' => 'admin#artist'
  get 'admin/tag/:id' => 'admin#tag'
  patch 'ajax/tag/update/:id' => 'genre#update'
  post 'ajax/video/hide' => 'admin#visibility'
  put 'admin/transfer' => 'admin#transferItem'
  post 'ajax/admin/process/all' => 'admin#batch_preprocessVideos'
  post 'ajax/admin/verify' => 'admin#verify_integrity'
  
  get 'view/:id' => 'video#view'
  get 'ajax/view/:id' => 'video#go_next'
  get 'embed/:id' => 'embed#view'
  get 'download/:id' => 'video#download'
  get 'upload' => 'video#upload'
  post 'ajax/upload/:async' => 'video#create'
  post 'ajax/upload' => 'video#create'
  get 'video/edit/:id' => 'video#edit'
  get 'videos/watched' => 'feed#view'
  get 'filters' => 'feed#edit'
  patch 'filters' => 'feed#update'
  get 'ajax/feed' => 'feed#page'
  get 'videos' => 'video#list'
  get 'ajax/videos' => 'video#page'
  get 'forum' => 'thread#list'
  get 'ajax/threads' => 'thread#page_threads'
  
  get 'profile/:id' => 'artist#view'
  get 'ajax/artist/hovercard' => 'artist#card'
  get 'ajax/artist/update/banner/:id' => 'artist#banner'
  post 'ajax/artist/lookup' => 'search#autofillArtist'
  patch 'ajax/update/artist' => 'artist#update'
  patch 'ajax/avatar/upload/:async' => 'artist#setavatar'
  patch 'ajax/avatar/upload' => 'artist#setavatar'
  patch 'ajax/banner/upload/:id/:async' => 'artist#setbanner'
  patch 'ajax/banner/upload/:id' => 'artist#setbanner'
  
  get 'cover/:id-small' => 'imgs#thumb'
  get 'cover/:id' => 'imgs#cover'
  get 'avatar/:id' => 'imgs#avatar'
  get 'banner/:id' => 'imgs#banner'
  get 'stream/:id' => 'imgs#stream', constraints: { id: /.*/ }
  
  get 'ajax/album/create' => 'album#new'
  get 'ajax/album/update/:id' => 'album#edit'
  get 'album/:id' => 'album#view'
  get 'albums' => 'album#list'
  get 'ajax/albums/items' => 'album#items'
  get 'ajax/albums' => 'album#page'
  
  post 'ajax/create/album' => 'album#create'
  patch 'ajax/edit/album/:id' => 'album#update_ordering'
  post 'ajax/update/album' => 'album#update'
  post 'ajax/delete/album/:id' => 'album#delete'
  
  get 'tags' => 'genre#list'
  get 'tags/:name', to: 'genre#view', constraints: { name: /.*/ }
  get 'ajax/find/tags' => 'genre#find'
  get 'ajax/genres' => 'genre#page'
  post 'ajax/tag/hide' => 'genre#hide'
  post 'ajax/tag/spoiler' => 'genre#spoiler'
  post 'ajax/tag/watch' => 'genre#watch'
  get 'ajax/tags/videos' => 'genre#videos'
  get 'ajax/tags/users' => 'genre#users'
  
  get 'ajax/reporter/:id' => 'admin#reporter'
  post 'ajax/reporter/:id' => 'admin#report'
  
  post 'ajax/like/:id(/:incr)' => 'ajax#upvote'
  post 'ajax/dislike/:id(/:incr)' => 'ajax#downvote'
  post 'ajax/video/togglealbum' => 'ajax#toggleAlbum'
  post 'ajax/video/feature' => 'ajax#toggleFeature'
  post 'ajax/star/:id' => 'ajax#star'
  post 'ajax/report/:id' => 'ajax#report'
  post 'report/:id' => 'admin#report'
  post 'report/:id/:async' => 'admin#report'
  
  post 'ajax/create/video' => 'video#create'
  patch 'ajax/update/video/:async' => 'video#updateCover'
  patch 'ajax/update/video' => 'video#updateCover'
  post 'ajax/update/video' => 'video#update'
  post 'ajax/delete/video/:id' => 'admin#deleteVideo'
  
  post 'ajax/create/albumitem' => 'album#addItem'
  post 'ajax/update/albumitem' => 'album#arrange'
  post 'ajax/delete/albumitem' => 'album#removeItem'
  
  post 'ajax/update/star' => 'album#arrangeStar'
  post 'ajax/delete/star' => 'album#removeStar'
  
  get 'notifications' => 'thread#notifications'
  
  get 'thread/:id' => 'thread#view'
  get 'ajax/thread/new' => 'thread#new'
  post 'ajax/create/thread' => 'thread#create'
  post 'ajax/update/thread' => 'thread#update'
  post 'ajax/thread/pin' => 'ajax#togglePin'
  post 'ajax/thread/lock' => 'ajax#toggleLock'
  post 'ajax/comments/new' => 'thread#post_comment'
  post 'ajax/comments/delete/:id' => 'thread#remove_comment'
  post 'ajax/comments/edit' => 'thread#edit_comment'
  get 'ajax/comments/get' => 'thread#get_comment'
  get 'ajax/comments/:thread_id/:order' => 'thread#page'
  
  get 'api/videos' => 'video#matching_videos'
  get 'api/video/get/:id' => 'video#video_details'
  post 'api/video/set/:id' => 'video#video_update'
  
  get '/' => 'welcome#index'
  root 'welcome#index'
end
